### ISSUE TITLE
Create Halaman Detail Mata Kuliah

### ISSUE THREAD

**Issue by akbarfadlika29** [agustinanisaf/SquareCheck-desktop#15]
What to do
---

References
---

![Halaman Detail Mata Kuliah – MVP](https://user-images.githubusercontent.com/31271087/101241709-2c393480-372b-11eb-919e-0f516a0f6813.png)

*_Jangan langsung merge, dicheck dulu sama system ada error apa enggak_

**Comment by ryuuzake** [comment]
Current View

![image](https://user-images.githubusercontent.com/31271087/101241815-137d4e80-372c-11eb-929e-e671ae87efca.png)

**Comment by ryuuzake** [comment]
Latest Update

![image](https://user-images.githubusercontent.com/31271087/101243625-1419e300-3734-11eb-9743-9ae3a3f5cb52.png)
