### ISSUE TITLE
Create Detail Kehadiran Matakuliah

### ISSUE THREAD

**Issue by rizabach29** [agustinanisaf/SquareCheck-desktop#17]
What to do
---

- [x] Controller
- [ ] View
- [x] UI

References
---

![Detail Kehadiran Mata Kuliah – MVP](https://user-images.githubusercontent.com/31271087/101241673-e54b3f00-372a-11eb-989c-fe69e5c53f9d.png)

*_Jangan langsung merge, dicheck dulu sama system ada error apa enggak_

**Comment by rizabach29** [comment]
@ryuuzake tulung cek, sama sek kurang navigation page

**Comment by ryuuzake** [comment]
Current View

![image](https://user-images.githubusercontent.com/31271087/101244424-0e72cc00-3739-11eb-8beb-769fa6e6e224.png)

@rizabach29 isok bok ganti datane, wes onok subject teko schedule sebelum e

**Comment by rizabach29** [comment]
Wokeyy
