### ISSUE TITLE
Create List Mahasiswa Per Jurusan MVC

### ISSUE THREAD

**Issue by rizabach29** [agustinanisaf/SquareCheck-desktop#5]
What to do
---

- [x] UI 
- [x] Model 
- [x] View 
- [x] Controller 

References
---

![List Mahasiswa setiap Jurusan](https://user-images.githubusercontent.com/31271087/101077542-8d4ff380-35d7-11eb-868d-761c972bf41f.png)

*_Jangan langsung merge, dicheck dulu sama system ada error apa enggak_

**Comment by ryuuzake** [comment]
@rizabach29 tampilan e kurang sing **breadcrumb** karo **search** (fitur search wes onok nak backend lek apene bok tambahno)
