### ISSUE TITLE
Create List Matkul Mahasiswa

### ISSUE THREAD

**Issue by AanMFA** [agustinanisaf/SquareCheck-desktop#9]
What to do
---
![List Matkul](https://user-images.githubusercontent.com/57135976/100312829-defbeb00-2fe5-11eb-9aec-0c3977ce5be4.PNG)

- [x] Model
- [x] View
- [x] Controller

References
---

*_Jangan langsung merge, dicheck dulu sama system ada error apa enggak_

**Comment by AanMFA** [comment]
@ryuuzake kurang cara ngganti page e ng item control, karo ngaccept studentmodel soko page sebelumnya

**Comment by ryuuzake** [comment]
@AanMFA Isok bok tambah endpoint buat get student e ben gak atek dummy

Tampilan setelah navigation jadi ngene:
![image](https://user-images.githubusercontent.com/31271087/101079265-d4d77f00-35d9-11eb-99a5-f77cc9070af5.png)

**Comment by AanMFA** [comment]
@ryuuzake insyaallah wes mari, kurang redirect bagian sg dipencet nunggu ke halaman yg mana

**Comment by ryuuzake** [comment]
@AanMFA good to pull request and merge
